    - name: Install sudo for escalated privileges
      package:
        name: sudo
        state: latest
      become_user: "root"
    - name: Create user "{{ user }}"
      user:
        home: "/home/{{ user }}/"
        name: "{{ user }}"
        password: "{{ passwd | password_hash('sha512', 'maSecretSalt$$__') }}"
        shell: /bin/bash
        uid: 1000
        groups: "{{ user_groups }}"
    - name: Enable sudo privilege
      lineinfile:
        state: present
        path: /etc/sudoers
        line: "{{ user }}     ALL=(ALL) NOPASSWD:ALL"
        create: yes
