    - debug:
        msg: "Creating user {{ user }}"
    - name: Add ansible group and extra groups for other purposes
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ user_groups }}"

    - name: Install sudo for escalated privileges
      package:
        name: sudo
        state: latest
      become_user: "root"
    - name: Create user "{{ user }}"
      user:
        home: "/home/{{ user }}/"
        name: "{{ user }}"
        password: "{{ passwd | password_hash('sha512', 'maSecretSalt$$__') }}"
        shell: /bin/bash
        groups: "{{ user_groups }}"
    - name: Enable sudo privilege
      lineinfile:
        state: present
        path: /etc/sudoers
        line: "{{ user }}     ALL=(ALL) NOPASSWD:ALL"
        create: yes
    - name: Add sudoers users to the ansible group
      user:
        name: ansible
        state: present
        group: ansible
        groups: ansible
        comment: "Ansible user"
      when: "user == 'ansible'"
