    - set_fact:
        packages_dir: "~/packages"
        screnshot_dir: "~/Pictures/Screenshots"
        mpd_dir: "~/.config/mpd"
        mpd_pl_dir: "~/.config/mpd/playlist"
    - name: Erase packages directory to start over
      file:
        path: "{{ packages_dir }}"
        state: absent
    - name: Ensure packages directory exists
      file:
        path: "{{ packages_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ user }}"
    - name: Clone all packages
      shell:
        cmd: "git clone {{ item }}"
        chdir: "{{ packages_dir }}"
      loop: "{{ packages_gits }}"
    - name: Makepkg and cleanup
      shell:
        cmd: "ls | xargs -I {} sh -c \"cd {}; makepkg -sic --noconfirm; cd -\""
        chdir: "{{ packages_dir }}"
