      - name: Check if i3 exists
        stat:
          path: "/usr/bin/i3"
        register: i3_register
      - name: Check if i3 socket exists
        stat:
          path: "/tmp/i3-ipc.sock"
        register: i3_socket_register
      - name: Preset for vim to be automatic
        replace:
          path: "~/.vimrc"
          regexp: "^colorscheme"
          replace: "\" colorscheme"
      - name: Preset for vim to be automatic
        replace:
          path: "~/.vimrc"
          regexp: "^Plug.*coc"
          replace: "\" Plug 'neoclide\/coc"
      - name: PlugUpdate and PlugInstall for vim
        shell:
          cmd: "vim +'PlugUpdate' +qa && vim +'PlugInstall' +qa"
          chdir: "~"
      - name: Source .vimrc
        shell:
          cmd: "vim +'source %' +qa"
          chdir: "~"
      - name: Set default shell to zsh
        shell:
          cmd: "usermod --shell /bin/zsh {{ user }}"
        become_user: "root"
      - name: Restart i3
        shell:
         cmd: "i3-msg reload"
        when: i3_register.stat.exists and i3_socket_register.stat.exists
      - name: Update Permission
        shell:
          cmd: "sudo chown -R {{ user }}:{{ user }} ~"
      - name: Kick you into ZSH
        shell:
          cmd: "zsh &"
