- name: Doom Machine - Thang's script To start a Computer up and running
  hosts: arch_two
  gather_facts: true

  vars:
    group_lists:
      - all

  vars_prompt:
    - name: user
      prompt: "Please Enter Your Username"
      private: no
      default: "tnguyen"
    - name: passwd
      prompt: "Please Enter Your Password"
      private: no
      default: "please"

  become: yes

  tasks:
    # - import_tasks: addUser.yml
    - import_tasks: build_packages.yml

