- name: Doom Machine - Thang's script To start a Computer up and running
  hosts: arch_one
  gather_facts: true

  vars:
    group_lists:
      - all

  vars_prompt:
    - name: user
      prompt: "Please Enter Your Username"
      private: no
      default: "tnguyen"
    - name: email
      prompt: "Please Enter Your Email"
      private: no
      default: "tnguye20@uvm.edu"
    - name: passwd
      prompt: "Please Enter Your Password"
      private: yes
      default: "please"

  become: yes

  tasks:
    - import_tasks: addUser.yml
    - block:
      - import_tasks: install-packages.yml
      - import_tasks: build_packages.yml
      - import_tasks: basicDir.yml
      - import_tasks: sshKey.yml
      - import_tasks: utilities_install.yml
      - import_tasks: dotfiles.yml
      - import_tasks: cleanup.yml
      become_user: "{{ user }}"

