- name: Doom Machine - Thang's script To start a Computer up and running
  hosts: arch_two
  gather_facts: true
  tasks:
    - name: Install Git
      package:
        name: git
        state: latest
    - name: Install sl
      package:
        name: cowsay
        state: latest
    - name: Get Scripts
      git:
        repo: 'https://github.com/tnguye20/scripts.git'
        clone: yes
        dest: /home/root/scripts

