      - name: Get my scripts
        git:
          repo: https://github.com/tnguye20/scripts.git
          dest: "~/scripts"
          clone: yes
          update: yes
          force: yes
        register: scripts_register

      - name: Get my dotfiles
        git:
          repo: https://github.com/tnguye20/.dotfiles.git
          dest: "~/.dotfiles"
          clone: yes
          update: yes
          force: yes
        register: dotfiles_register
      - name: Check post-merge hook for conflict
        stat:
          path: "~/.dotfiles/.githooks"
        register: pm_register

      - name: Init LFS
        shell:
          cmd: "git lfs install"
          chdir: "~/.dotfiles"
        when: pm_register.stat.exists == False
      - name: Pull LFS files
        shell:
          cmd: "git lfs pull"
          chdir: "~/.dotfiles"
        when: pm_register.stat.exists == False

      - name: Symlink .vimrc
        file:
          force: yes
          src: "~/.dotfiles/.vimrc"
          dest: "~/.vimrc"
          state: link
      - name: Symlink .zshrc
        file:
          force: yes
          src: "~/.dotfiles/.zshrc"
          dest: "~/.zshrc"
          state: link
      - name: Symlink .tridactylrc
        file:
          force: yes
          src: "~/.dotfiles/.tridactylrc"
          dest: "~/.tridactylrc"
          state: link
      - name: Symlink i3 config
        file:
          force: yes
          src: "~/.dotfiles/.i3/config"
          dest: "~/.i3/config"
          state: link
      - name: Symlink mpd config
        file:
          force: yes
          src: "~/.dotfiles/.config/mpd/mpd.conf"
          dest: "~/.config/mpd/mpd.conf"
          state: link
      - name: Symlink ranger config
        file:
          force: yes
          src: "~/.dotfiles/.config/ranger/rc.conf"
          dest: "~/.config/ranger/rc.conf"
          state: link
      - name: Symlink .gitconfig
        file:
          force: yes
          src: "~/.dotfiles/.gitconfig"
          dest: "~/.gitconfig"
          state: link
      - name: Symlink .profile
        file:
          force: yes
          src: "~/.dotfiles/.profile"
          dest: "~/.profile"
          state: link
      - name: Symlink cool-retro-term profiles
        file:
          force: yes
          src: "~/.dotfiles/.cool-retro-term"
          dest: "~/.cool-retro-term"
          state: link
      - name: Symlink Xresources for urxvt
        file:
          force: yes
          src: "~/.dotfiles/.Xresources"
          dest: "~/.Xresources"
          state: link
