- name: Installation of Apps
  hosts: arch
  gather_facts: true
  tasks:
    - name: Please Check This
      command: echo "Please"
      register: please_var
    - name: Debug this process
      debug: var=please_var
    - name: Install sl
      pacman:
        name: sl
        state: latest
      become: true
    - name: Install cowsay
      pacman:
        name: sl
        state: latest
