      - set_fact:
          ssh_dir: "~/.ssh"
          ssh_cmds: [
            "ssh-keygen -t rsa -b 4096 -C \"{{ email }}\" -q -N '' -f ~/.ssh/id_rsa",
            "eval \"$(ssh-agent -s)\"",
            "ssh-add",
          ]
      - name: SSH Key Dir Creation
        file:
          path: "{{ ssh_dir }}"
          state: directory
          mode: "0700"
        register: ssh_dir_register
      - name: SSH Key Creation
        shell:
          cmd: "{{ item }}"
          chdir: "{{ ssh_dir }}"
        loop: "{{ ssh_cmds }}"
        when: ssh_dir_register.changed
